language: php

php:
  - 7.1

install:
  - composer self-update
  - composer install
  - wget -c -nc --retry-connrefused --tries=0 https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - chmod +x coveralls.phar
  - php coveralls.phar --version
  - yarn

before_script:
  - npm install -g gulp-cli
  - mkdir -p build/logs
  - ls -al

script:
  - phpunit --bootstrap vendor/autoload.php --colors=always --whitelist=core/ --coverage-clover build/logs/clover.xml core/tests/
  - gulp
  - npm test
  - npm run coveralls

after_success:
 - travis_retry php coveralls.phar -v

notifications:
  email: false
  webhooks:
    urls:
      - https://ci.miloszdura.com/deploy/ci
    on_start: always
    on_success: always
    on_failure: always