language: php

php:
  - 7.1

before_script:
  - composer self-update
  - composer install

script: phpunit --bootstrap vendor/autoload.php --colors=always core/Tests/

notifications:
    email: false
  webhooks:
    - https://ci.miloszdura.com/deploy/ci
  on_success: always